### ISSUE TITLE
404 List

### ISSUE THREAD

**Issue by zacharyno** [AndydeCleyre/bookme#1]
Works great. I did get 404s on the below. Not sure if I should try again or if it is just server side, but FYI

FAILURE 10.1007/978-1-4020-6808-9 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4020-6808-9.epub
FAILURE 10.1007/978-0-387-40065-5 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-0-387-40065-5.epub
FAILURE 10.1007/b104645 EPUB 404 https://link.springer.com/download/epub/10.1007%2Fb104645.epub
FAILURE 10.1007/978-0-387-84858-7 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-0-387-84858-7.epub
FAILURE 10.1007/978-1-4419-7288-0 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4419-7288-0.epub
FAILURE 10.1007/978-1-4419-9982-5 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4419-9982-5.epub
FAILURE 10.1007/978-3-540-32899-5 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-540-32899-5.epub
FAILURE 10.1007/978-0-387-87573-6 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-0-387-87573-6.epub
FAILURE 10.1007/978-1-4757-2519-3 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4757-2519-3.epub
FAILURE 10.1007/978-0-387-88698-5 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-0-387-88698-5.epub
FAILURE 10.1007/978-3-642-30319-7 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-642-30319-7.epub
FAILURE 10.1007/978-3-662-56272-7 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-662-56272-7.epub
FAILURE 10.1007/978-3-662-56509-4 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-662-56509-4.epub
FAILURE 10.1007/978-3-540-93804-0 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-540-93804-0.epub
FAILURE 10.1007/978-3-662-44874-8 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-662-44874-8.epub
FAILURE 10.1007/978-1-4612-1844-9 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4612-1844-9.epub
FAILURE 10.1007/978-90-481-2516-6 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-90-481-2516-6.epub
FAILURE 10.1007/978-0-387-79054-1 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-0-387-79054-1.epub
FAILURE 10.1007/978-3-319-12742-2 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-319-12742-2.epub
FAILURE 10.1007/978-3-642-04101-3 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-642-04101-3.epub
FAILURE 10.1007/978-3-642-20059-5 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-642-20059-5.epub
FAILURE 10.1007/978-1-4613-0139-4 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4613-0139-4.epub
FAILURE 10.1007/978-1-4419-6646-9 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4419-6646-9.epub
FAILURE 10.1007/978-1-84628-642-1 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-84628-642-1.epub
FAILURE 10.1007/0-387-36274-6 EPUB 404 https://link.springer.com/download/epub/10.1007%2F0-387-36274-6.epub
FAILURE 10.1007/978-0-387-75959-3 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-0-387-75959-3.epub
FAILURE 10.1007/978-3-540-69934-7 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-540-69934-7.epub
FAILURE 10.1007/0-387-28117-7 EPUB 404 https://link.springer.com/download/epub/10.1007%2F0-387-28117-7.epub
FAILURE 10.1007/978-1-4757-0576-8 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4757-0576-8.epub
FAILURE 10.1007/978-3-319-55444-0 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-319-55444-0.epub
FAILURE 10.1007/0-387-36218-5 EPUB 404 https://link.springer.com/download/epub/10.1007%2F0-387-36218-5.epub
FAILURE 10.1007/978-3-319-63588-0 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-319-63588-0.epub
FAILURE 10.1007/b99417 EPUB 404 https://link.springer.com/download/epub/10.1007%2Fb99417.epub
FAILURE 10.1007/978-3-319-91041-3 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-319-91041-3.epub
SUCCESS 10.1007/978-3-319-44048-4 EPUB 2016_Book_StatisticalLearningFromARegres.epub
FAILURE 10.1007/978-3-540-27752-1 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-540-27752-1.epub
FAILURE 10.1007/978-3-658-07884-3 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-658-07884-3.epub
FAILURE 10.1007/978-3-319-66631-0 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-319-66631-0.epub
FAILURE 10.1007/978-1-4612-4374-8 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4612-4374-8.epub
FAILURE 10.1007/978-3-030-03255-5 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-030-03255-5.epub
FAILURE 10.1007/978-0-387-72579-6 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-0-387-72579-6.epub
FAILURE 10.1007/978-1-4419-9479-0 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4419-9479-0.epub
FAILURE 10.1007/978-3-642-30250-3 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-642-30250-3.epub
FAILURE 10.1007/978-3-319-21936-3 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-319-21936-3.epub
FAILURE 10.1007/978-1-84800-070-4 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-84800-070-4.epub
FAILURE 10.1007/978-1-4471-6684-9 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4471-6684-9.epub
FAILURE 10.1007/978-3-319-11080-6 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-319-11080-6.epub
FAILURE 10.1007/978-0-387-37575-5 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-0-387-37575-5.epub
FAILURE 10.1007/978-1-84800-322-4 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-84800-322-4.epub
FAILURE 10.1007/978-1-4020-6099-1 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4020-6099-1.epub
FAILURE 10.1007/978-0-387-32353-4 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-0-387-32353-4.epub
FAILURE 10.1007/978-1-84882-935-0 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-84882-935-0.epub
FAILURE 10.1007/978-3-662-43715-5 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-662-43715-5.epub
FAILURE 10.1007/1-84628-168-7 EPUB 404 https://link.springer.com/download/epub/10.1007%2F1-84628-168-7.epub
FAILURE 10.1007/b100507 EPUB 404 https://link.springer.com/download/epub/10.1007%2Fb100507.epub
FAILURE 10.1007/978-94-007-6113-1 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-94-007-6113-1.epub
FAILURE 10.1007/978-1-4612-4360-1 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4612-4360-1.epub
FAILURE 10.1007/978-1-4612-1272-0 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-1-4612-1272-0.epub
FAILURE 10.1007/978-3-540-77974-2 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-540-77974-2.epub
FAILURE 10.1007/978-3-662-57265-8 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-3-662-57265-8.epub
FAILURE 10.1007/978-0-387-44899-2 EPUB 404 https://link.springer.com/download/epub/10.1007%2F978-0-387-44899-2.epub
FAILURE 10.1007/b100747 EPUB 404 https://link.springer.com/download/epub/10.1007%2Fb100747.epub

**Comment by AndydeCleyre** [comment]
I spot-checked a few of those, and they're not available as epubs on the site (see, e.g. https://link.springer.com/book/10.1007/978-1-4020-6808-9 ).

If you chose epub as your preferred format, the script should note that it wasn't found, and get the PDF instead -- did it?

**Comment by AndydeCleyre** [comment]
A recent change now logs the human-friendly page for each failed download for easier inspection, btw.

**Comment by AndydeCleyre** [comment]
OK I'm going to assume for now that it's doing the right thing, just encountering books without epub files provided by Springer. Please re-open if this is not the case.
